### ISSUE TITLE
🤔 Why need to delete the header's content-length?

### ISSUE THREAD

**Issue by nonjene** [leumasme/koa-forwardproxy#1]
Hey, I am studying this repo, and can't figure out this one, why do need to delete the `content-length`?
https://github.com/leumasme/koa-forwardproxy/blob/1900ecf8f5384be427b136ff474e493c8dc3c2ac/src/index.ts#L58

**Comment by leumasme** [comment]
Hi, thanks for your interest in this project!
When leaving the content-length header in, i had issues in the proxied response body from the server to the client webbrowser getting cut off early (some bytes simply missing at the end) - maybe because of compression stuff? I'm not sure, but deleting the header seemed to fix it, so i just left it like that. Koa automatically generates a content-length header anyways if its missing.
I've just had issues with encoding at the end - if you get your project to work, let me know!
